version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: banknot-postgres
    environment:
      POSTGRES_USER: banknot
      POSTGRES_PASSWORD: banknot
      POSTGRES_DB: banknot
    ports:
      - "5432:5432"
    volumes:
      - banknot-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "banknot"]
      interval: 5s
      timeout: 3s
      retries: 10
  adminer:
    image: adminer:4
    container_name: banknot-adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
volumes:
  banknot-pg-data:
    driver: local
